version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleanflow
      POSTGRES_HOST_AUTH_METHOD: trust # Modo de autenticación para desarrollo (Cambiar en producción)
    ports:
      - "5433:5432" # Mapeo del puerto 5433 del host al 5432 del contenedor (Evitar conflicto con Postgres local)
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
